examples: remove local libfdt_env.h file
A recent dtc commit (142419) require use
of the libfdt_env.h provided by libfdt
itself otherwise the compiler generates
errors like these:

fdt.h:58:2: error: expected specifier-qualifier-list before 'fdt32_t'
fdt.h:77:2: error: expected specifier-qualifier-list before 'fdt64_t'
libfdt.h: In function 'fdt_set_magic':
libfdt.h:162:116: error: 'struct fdt_header' has no member named 'magic'
[...]

To fix we could either update the local file with
the new types or just remove the local, incomplete
clone so the dtc provided version gets used.
This patch goes the simpler way and removes
the files.

Signed-off-by: Laurentiu Tudor <Laurentiu.Tudor@freescale.com>